import{a as S,i as u,S as w}from"./assets/vendor-940309d5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const M="3024031-50bf2ca6b1e9bc3513f045fb3";async function y(r,e){let s=15;const t=`https://pixabay.com/api/?${new URLSearchParams({key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:s,page:e}).toString()}`;return S.get(t)}const L=document.querySelector(".form"),a=document.querySelector(".gallery"),l=document.querySelector(".loader"),i=document.querySelector(".load-more-images-btn"),P=document.querySelector("#user-search-input");i.classList.add("is-hidden");let d="",c=1;const b=()=>{document.querySelector(".bottom-scroll").scrollIntoView({behavior:"smooth"})},q=()=>{document.querySelector(".top-scroll").scrollIntoView({behavior:"smooth"})},v=r=>new w(r,{focus:!0,captionsData:"alt",captionDelay:250});function g(r){return r.map(s=>`
    <li class="gallery-item">
    <div class="img-container">
          <a  class="image-link" href="${s.largeImageURL}"><img class="image" src="${s.webformatURL}" alt="${s.tags}" />
          </div>
          <ul class="under-picture-list">
              <li class="under-picture-info-item">Likes <span class="data-received">${s.likes}</span></li>
              <li class="under-picture-info-item">Views <span class="data-received">${s.views}</span></li>
              <li class="under-picture-info-item">Comments <span class="data-received">${s.comments}</span></li>
              <li class="under-picture-info-item">Downloads <span class="data-received">${s.downloads}</span></li>
          </ul>
      </li> 
      </a>`).join("")}const m=()=>{i.classList.add("is-hidden"),i.removeEventListener("click",f)},I=()=>{i.classList.remove("is-hidden"),i.addEventListener("click",f)},h=(r,e)=>{a.innerHTML="",r.reset(),u.error({message:e,position:"topRight",timeout:2e3}),m()},f=async r=>{try{c+=1;const e=await y(d,c);a.insertAdjacentHTML("beforeend",g(e.data.hits)),v(".image-link").refresh(),b();let n=Math.ceil(e.data.totalHits/15);c===n&&(m(),u.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),setTimeout(()=>{q()},5e3)),l.classList.remove("is-visible")}catch(e){console.log(e)}},E=async r=>{try{if(r.preventDefault(),d=r.target.elements.picture_search.value.trim(),d===""){h(r.target,"Please enter a query.");return}c=1,a.innerHTML="",l.classList.add("is-visible");const e=await y(d,c);if(l.classList.remove("is-visible"),P.value="",e.data.hits.length===0){h(r.target,u.error({message:"Sorry, there are no images matching your search query. Please try again."}));return}a.insertAdjacentHTML("beforeend",g(e.data.hits));let s=v(".image-link");if(s.refresh(),e.data.totalHits<=15){m();return}e.data.totalHits>15&&(a.innerHTML=g(e.data.hits),s.refresh(),I(),i.addEventListener("click",f),b())}catch(e){l.classList.remove("is-visible"),console.log(e)}};L.addEventListener("submit",E);L.addEventListener("reset",()=>{a.innerHTML="",m(),u.info({message:"Search reset. Please enter a new query.",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
