import{a as w,i as c,S as y}from"./assets/vendor-cb8926f2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&l(p)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const S="3024031-50bf2ca6b1e9bc3513f045fb3";async function L(t,e){const l=`https://pixabay.com/api/?${new URLSearchParams({key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e}).toString()}`;return w.get(l)}const v=document.querySelector(".form"),a=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".load-more-images-btn"),M=document.querySelector("#user-search-input");i.classList.add("is-hidden");let u="",n=1;const b=()=>{document.querySelector(".bottom-scroll").scrollIntoView({behavior:"smooth"})},q=()=>{document.querySelector(".top-scroll").scrollIntoView({behavior:"smooth"})},P=t=>new y(t,{focus:!0,captionsData:"alt",captionDelay:250});function g(t){return t.map(s=>`
    <li class="gallery-item">
    <div class="img-container">
          <a  class="image-link" href="${s.largeImageURL}"><img class="image" src="${s.webformatURL}" alt="${s.tags}" />
          </div>
          <ul class="under-picture-list">
              <li class="under-picture-info-item">Likes <span class="data-received">${s.likes}</span></li>
              <li class="under-picture-info-item">Views <span class="data-received">${s.views}</span></li>
              <li class="under-picture-info-item">Comments <span class="data-received">${s.comments}</span></li>
              <li class="under-picture-info-item">Downloads <span class="data-received">${s.downloads}</span></li>
          </ul>
      </li> 
      </a>`).join("")}const m=()=>{i.classList.add("is-hidden"),i.removeEventListener("click",f)},I=()=>{i.classList.remove("is-hidden"),i.addEventListener("click",f)},h=(t,e)=>{a.innerHTML="",t.reset(),c.error({message:e,position:"topRight",timeout:2e3}),m()},f=async t=>{try{n+=1;const e=await L(u,n);a.insertAdjacentHTML("beforeend",g(e.data.hits)),new y(".image-link",{focus:!0,captionsData:"alt",captionDelay:250}),b();let s=Math.ceil(e.data.totalHits/15);n===s&&(m(),c.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),setTimeout(()=>{q()},5e3)),d.classList.remove("is-visible")}catch(e){console.log(e)}},E=async t=>{try{if(t.preventDefault(),u=t.target.elements.picture_search.value.trim(),u===""){h(t.target,"Please enter a query.");return}n=1,a.innerHTML="",d.classList.add("is-visible");const e=await L(u,n);if(d.classList.remove("is-visible"),M.value="",e.data.hits.length===0){h(t.target,c.error({message:"Sorry, there are no images matching your search query. Please try again."}));return}a.insertAdjacentHTML("beforeend",g(e.data.hits));let s=P(".image-link");s.refresh(),e.data.totalHits<=15&&(m(),c.info({message:"No more images to load.",position:"topRight"})),e.data.totalHits>15&&(a.innerHTML=g(e.data.hits),s.refresh(),I(),i.addEventListener("click",f),b())}catch(e){d.classList.remove("is-visible"),console.log(e)}};v.addEventListener("submit",E);v.addEventListener("reset",()=>{a.innerHTML="",m(),c.info({message:"Search reset. Please enter a new query.",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
