import{a as I,i as S,S as b}from"./assets/vendor-06e2593d.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const o of i.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function s(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(r){if(r.ep)return;r.ep=!0;const i=s(r);fetch(r.href,i)}})();const x="3024031-50bf2ca6b1e9bc3513f045fb3";async function v(e,t){let s=15;const r=`https://pixabay.com/api/?${new URLSearchParams({key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:s,page:t}).toString()}`;return I.get(r)}const D=()=>{var e;(e=document.querySelector(".bottom-scroll"))==null||e.scrollIntoView({behavior:"smooth"})},$=e=>e.map(t=>`
  <li class="gallery-item">
    <div class="img-container">
      <a class="image-link" href="${t.largeImageURL}">
        <img class="image" src="${t.webformatURL}" alt="${t.tags}" />
      </a>
    </div>
    <ul class="under-picture-list">
      <li class="under-picture-info-item">Likes <span class="data-received">${t.likes}</span></li>
      <li class="under-picture-info-item">Views <span class="data-received">${t.views}</span></li>
      <li class="under-picture-info-item">Comments <span class="data-received">${t.comments}</span></li>
      <li class="under-picture-info-item">Downloads <span class="data-received">${t.downloads}</span></li>
    </ul>
  </li>
`).join(""),u=(e,t,s)=>{e.innerHTML="",t.reset(),S.error({message:s,position:"topRight",timeout:2e3})},L=e=>{e.classList.add("is-hidden"),e.replaceWith(e.cloneNode(!0))},P=(e,t)=>{e.classList.remove("is-hidden"),e.innerHTML=`<span class="load-more-text">${t}</span>`},q=e=>{e.classList.add("is-visible")},m=e=>{e.classList.remove("is-visible")},M=(e,t="topRight",s=5e3)=>{S.show({message:e,position:t,timeout:s})};document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".form"),t=document.querySelector(".gallery"),s=document.querySelector(".loader"),n=document.querySelector(".load-more-images-btn"),r=document.querySelector(".scroll-to-top-btn");n.classList.add("is-hidden");const i=document.querySelector("#user-search-input");let o=1,g=0,l=0,f=0,p="";const d=15;let h=`Load more images ${l-o*d} of ${l}`,y=new b(".image-link",{captionsData:"alt",captionDelay:250});n.classList.add("is-hidden");const E=async a=>{try{if(a.preventDefault(),p=a.target.elements.picture_search.value.trim(),o=1,y||(y=new b(".image-link",{focus:!0,captionsData:"alt",captionDelay:250})),p===""){u(a.target,"Please enter a query.");return}t.innerHTML="",q(s);const c=await v(p,o,d);if(console.log(c),l=c.data.total,c.status!==200){m(s),u(a.target,"Error fetching images. Please try again.");return}if(!c||!c.data){u(a.target,"No images found. Please enter another query.");return}if(m(s),i.value="",c.data.hits.length===0){u(a.target,"No images found. Please enter another query.");return}t.innerHTML=$(c.data.hits),y.refresh(),f=c.data.totalHits,console.log(`Total hits: ${f}`),g=Math.ceil(f/d),console.log(`Total pages: ${g}`),f<=d?(L(),M("We're sorry, but you've reached the end of search results.")):(h=`Load more images ${l-o*d} of ${l}`,P(n,h))}catch(c){m(s),h=`Load more images ${l-o*d} of ${l}`,L(n),u(a.target,"Error fetching images. Please try again."),console.error(c)}},T=async()=>{try{o++,q(s),h=`Load more images ${l-o*d} of ${l}`;const a=await v(p,o,d);if(console.log(o,g),a.status!==200){m(s),u(target,"Error fetching images. Please try again.");return}if(!a||!a.data){u(target,"No images found. Please enter another query.");return}m(s),t.insertAdjacentHTML("beforeend",$(a.data.hits)),y.refresh(),D();const w=`Load more images ${l-o*d} of ${l}`;o>=g?(L(n),M("We're sorry, but you've reached the end of search results.")):P(n,w)}catch(a){m(s),console.error(a)}};e.addEventListener("submit",E),n.addEventListener("click",T),window.addEventListener("scroll",()=>{window.scrollY>400?r.classList.remove("is-hidden"):r.classList.add("is-hidden")}),r.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})});
//# sourceMappingURL=commonHelpers.js.map
